version: "3.8"
services:
  app:
    container_name: gpt-email-api
    image: vontainment/gpt-email-api:main # Use your appropriate image
    hostname: gpt-email-api
    restart: unless-stopped
    network_mode: bridge
    ports:
      - "8050:8888" # Map port 80 of the container to port 8075 on the host
    environment:
      BASE_URL: https://api.servicesbyv.com  # Set this to your actual base URL
      ROOT_PATH: /email
      API_KEY: "Optional API key to connect to api"  # Optional API key to connect to API
      WORKERS: 1  # uvicorn workers; 1 should be enough for personal use
      UVICORN_CONCURRENCY: 32  # Controls max connections. Requests over API_CONCURRENCY are queued or rejected.
      ACCOUNT_EMAIL: user1@example.com
      ACCOUNT_PASSWORD: password1
      ACCOUNT_IMAP_SERVER: imap.example.com
      ACCOUNT_IMAP_PORT: 993
      ACCOUNT_SMTP_SERVER: smtp.example.com
      ACCOUNT_SMTP_PORT: 587
      ACCOUNT_REPLY_TO: replyto@example.com
