[project]
name = "V-GPT-EMAIL-API"
description = "The v-gpt-email-api is a sophisticated email management system designed to enhance productivity by integrating GPT-powered functionalities. It facilitates intelligent email handling, including drafting responses, sorting, and automating common tasks based on user preferences and historical data. Built with FastAPI and containerized through Docker, the API ensures secure and compliant email transmission, with robust validation and error-handling mechanisms. Its primary value lies in streamlining user workflows and personalizing email interactions, making it a valuable tool for efficient and intelligent email management in modern work environments."
license = "MIT"
author = "Vontainment"
email = "services@vontainment.com"
repository = "https://github.com/djav1985/v-gpt-email-api"

[readme]
# Control the sections and order
sections = [
  "title",
  "description",
  "installation",
  "usage",
  "features",
  "license"
]

# Formatting options
output = "README.md"
logo = "llm"                 # "blue", "purple", "custom", etc.
badge_style = "flat-square"
header_style = "classic"
navigation_style = "number"
tree_max_depth = 5
emojis = "solar"                # theme or true/false
align = "center"                # left or center

[ai]
# Tell ReadmeAI to use the OpenAI-compatible API (GitHub Models under the hood)
provider = "openai"
model = "gpt-4o-mini"
temperature = 0.7
max_tokens = 1800

[ignore]
patterns = [
  "tests/",
  ".git/",
  "docs/"
]